application:
  config:
    description: Profile Production

server:
  port: 10084
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  application:
    name: service-credit
  cloud:
    config:
      profile: prod

  data:
    mongodb:
      uri: mongodb+srv://guisado:NakrF75eb7Ais6oH@clustermongo.ojl3e.mongodb.net/db

#Eureka Client
eureka:
  client:
    service-url:
      defaultZone: https://bootcamp2022-ms-eureka.azurewebsites.net:443/eureka
    #enabled: false
  instance:
    hostname: bootcamp2022-ms-credit.azurewebsites.net
    secure-port-enabled: true
    nonsecure-port-enabled: false
    nonSecurePort: 80
    securePort: 443

#Endpoints Eureka URL
config-eureka:
  base:
    customer:
      endpoint: 'http://service-customer/api/v1/customer'