application:
  config:
    description: Profile Production

server:
  port: 10090
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  application:
    name: service-report
  cloud:
    config:
      profile: prod

  data:
    mongodb:
      uri: mongodb+srv://guisado:NakrF75eb7Ais6oH@clustermongo.ojl3e.mongodb.net/db

#Endpoints
config:
  base:
    customer:
      endpoint: http://localhost:10082/api/v1/customer
    account:
      endpoint: http://localhost:10083/api/v1/account
    credit:
      endpoint: http://localhost:10084/api/v1/credit
    debitCard:
      endpoint: http://localhost:10088/api/v1/debitCard

#Eureka Client
eureka:
  client:
    service-url:
      defaultZone: https://bootcamp2022-ms-eureka.azurewebsites.net:443/eureka
    #enabled: false
  instance:
    hostname: bootcamp2022-ms-report.azurewebsites.net
    secure-port-enabled: true
    nonsecure-port-enabled: false
    nonSecurePort: 80
    securePort: 443

#Endpoints Eureka URL
config-eureka:
  base:
    customer:
      endpoint: 'http://service-customer/api/v1/customer'
    account:
      endpoint: 'http://service-account/api/v1/account'
    credit:
      endpoint: 'http://service-credit/api/v1/credit'
    debitCard:
      endpoint: 'http://service-card/api/v1/debitCard'
    movement:
      endpoint: 'http://service-movements/api/v1/movement'