application:
  config:
    description: Profile Production

server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  application:
    name: service-bootcointx
  cloud:
    config:
      profile: dev

  data:
    mongodb:
      database: 'bootcoindbtx'
      host: 'localhost'
      port: 27017

#kafka
kafka:
  uri: '127.0.0.1:9092'
  topic:
    topicTransactionAcceptance: TOPIC-Transaction-Acceptance

#Endpoints
config:
  base:
    customer:
      endpoint: http://localhost:10082/api/v1/customer
    account:
      endpoint: http://localhost:10083/api/v1/account
    credit:
      endpoint: http://localhost:10084/api/v1/credit

#Eureka Client
eureka:
  client:
    service-url:
      defaultZone: https://bootcamp2022-ms-eureka.azurewebsites.net:443/eureka
    #enabled: false
  instance:
    hostname: bootcamp2022-ms-bootcointx.azurewebsites.net
    secure-port-enabled: true
    nonsecure-port-enabled: false
    nonSecurePort: 80
    securePort: 443
    statusPageUrl: https://${eureka.hostname}:443/actuator/info
    healthCheckUrl: https://${eureka.hostname}:443/actuator/health
    secureHealthCheckUrl: https://${eureka.hostname}:443/actuator/health

#Endpoints Eureka URL
config-eureka:
  base:
    customer:
      endpoint: 'http://service-customer/api/v1/customer'
    account:
      endpoint: 'http://service-account/api/v1/account'
    credit:
      endpoint: 'http://service-credit/api/v1/credit'