application:
  config:
    description: Profile Development

server:
  port: 8083

spring:
  application:
    name: service-account
  cloud:
    config:
      profile: dev

  data:
    mongodb:
      database: 'accountdb'
      host: 'localhost'
      port: 27017

#Endpoints
config:
  base:
    customer:
      endpoint: 'http://localhost:8082/customerType/1'

#Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka
    #enabled: false