application:
  config:
    description: Profile Production

server:
  port: 10083
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  application:
    name: service-account
  cloud:
    config:
      profile: prod

  data:
    mongodb:
      uri: mongodb+srv://guisado:NakrF75eb7Ais6oH@clustermongo.ojl3e.mongodb.net/db

#Eureka Client
eureka:
  client:
    service-url:
      defaultZone: https://bootcamp2022-ms-eureka.azurewebsites.net/eureka
    #enabled: false

#Endpoints
config:
  base:
    customer:
      endpoint: 'http://localhost:10082/api/v1/customer'
    account:
      endpoint: http://localhost:10083/api/v1/account
    credit:
      endpoint: http://localhost:10084/api/v1/credit

#Endpoints Eureka URL
config-eureka:
  base:
    customer:
      endpoint: 'http://service-customer/api/v1/customer'
    account:
      endpoint: 'http://service-account/api/v1/account'
    credit:
      endpoint: 'http://service-credit/api/v1/credit'