application:
  config:
    description: Profile Production

server:
  port: 10082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  application:
    name: service-customer
  cloud:
    config:
      profile: prod

  data:
    mongodb:
      database: 'customerdb'
      host: 'localhost'
      port: 27017

#Eureka Client
eureka:
  client:
    service-url:
      defaultZone: https://bootcamp2022-ms-eureka.azurewebsites.net/eureka
    #enabled: false
  instance:
    hostname: bootcamp2022-ms-eureka.azurewebsites.net
    secure-port-enabled: true
    nonsecure-port-enabled: false
    nonSecurePort: 80
    securePort: 443