application:
  config:
    description: Profile Test

server:
  port: 9083

spring:
  application:
    name: service-account
  cloud:
    config:
      profile: dev

  data:
    mongodb:
      database: 'accountdb'
      host: 'localhost'
      port: 27017

#Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka
    #enabled: false

#Endpoints
config:
  base:
    customer:
      endpoint: 'http://localhost:9082/api/v1/customer'

#Endpoints Eureka URL
config-eureka:
  base:
    customer:
      endpoint: 'http://service-customer/api/v1/customer'