application:
  config:
    description: Profile Testing

server:
  port: 9085
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  application:
    name: service-movements
  cloud:
    config:
      profile: qa

  data:
    mongodb:
      database: 'movementsdb'
      host: 'localhost'
      port: 27017

#Endpoints
config:
  base:
    customer:
      endpoint: http://localhost:9082/api/v1/customer
    account:
      endpoint: http://localhost:9083/api/v1/account
    credit:
      endpoint: http://localhost:9084/api/v1/credit

#Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka
    #enabled: false

#Endpoints Eureka URL
config-eureka:
  base:
    customer:
      endpoint: 'http://service-customer/api/v1/customer'
    account:
      endpoint: 'http://service-account/api/v1/account'
    credit:
      endpoint: 'http://service-credit/api/v1/credit'