application:
  config:
    description: Profile Developer

server:
  port: 8084

spring:
  application:
    name: service-credit
  cloud:
    config:
      profile: dev

  data:
    mongodb:
      database: 'creditdb'
      host: 'localhost'
      port: 27017

#Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka
    #enabled: false